"""Add telegram_chat_id

Revision ID: 02f2594446ed
Revises: 92c32d07a4f7
Create Date: 2026-05-27 19:52:23.925205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02f2594446ed'
down_revision: Union[str, Sequence[str], None] = '92c32d07a4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_auth_user', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_auth_user', 'telegram_chat_id')
    # ### end Alembic commands ###
