"""Add reports tables and columns

Revision ID: 507d2c45ac8d
Revises: bf5789aea121
Create Date: 2026-06-12 16:31:33.741677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507d2c45ac8d'
down_revision: Union[str, Sequence[str], None] = 'bf5789aea121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_stock_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['tbl_book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_auth_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tbl_book', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    op.add_column('tbl_order_item', sa.Column('cost_price_at_purchase', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_order_item', 'cost_price_at_purchase')
    op.drop_column('tbl_book', 'cost_price')
    op.drop_table('tbl_stock_history')
    # ### end Alembic commands ###
