""" add tbl_system_log

Revision ID: 54845e35d29e
Revises: d6fc571cf35d
Create Date: 2026-06-28 15:32:48.107828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54845e35d29e'
down_revision: Union[str, Sequence[str], None] = 'd6fc571cf35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_system_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_auth_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_system_log_action'), 'tbl_system_log', ['action'], unique=False)
    op.create_index(op.f('ix_tbl_system_log_created_at'), 'tbl_system_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_tbl_system_log_level'), 'tbl_system_log', ['level'], unique=False)
    op.create_index(op.f('ix_tbl_system_log_module'), 'tbl_system_log', ['module'], unique=False)
    op.create_index(op.f('ix_tbl_system_log_user_id'), 'tbl_system_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_system_log_user_id'), table_name='tbl_system_log')
    op.drop_index(op.f('ix_tbl_system_log_module'), table_name='tbl_system_log')
    op.drop_index(op.f('ix_tbl_system_log_level'), table_name='tbl_system_log')
    op.drop_index(op.f('ix_tbl_system_log_created_at'), table_name='tbl_system_log')
    op.drop_index(op.f('ix_tbl_system_log_action'), table_name='tbl_system_log')
    op.drop_table('tbl_system_log')
    # ### end Alembic commands ###
