"""add performance indexes

Revision ID: 70a7538b9e86
Revises: b05b50d48755
Create Date: 2026-06-16 22:22:23.784869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a7538b9e86'
down_revision: Union[str, Sequence[str], None] = 'b05b50d48755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tbl_book_author'), 'tbl_book', ['author'], unique=False)
    op.create_index(op.f('ix_tbl_book_is_active'), 'tbl_book', ['is_active'], unique=False)
    op.create_index(op.f('ix_tbl_book_title'), 'tbl_book', ['title'], unique=False)
    op.create_index(op.f('ix_tbl_cart_item_book_id'), 'tbl_cart_item', ['book_id'], unique=False)
    op.create_index(op.f('ix_tbl_cart_item_user_id'), 'tbl_cart_item', ['user_id'], unique=False)
    op.create_index(op.f('ix_tbl_order_created_at'), 'tbl_order', ['created_at'], unique=False)
    op.create_index(op.f('ix_tbl_order_status'), 'tbl_order', ['status'], unique=False)
    op.create_index(op.f('ix_tbl_order_user_id'), 'tbl_order', ['user_id'], unique=False)
    op.create_index(op.f('ix_tbl_wishlist_book_id'), 'tbl_wishlist', ['book_id'], unique=False)
    op.create_index(op.f('ix_tbl_wishlist_user_id'), 'tbl_wishlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_wishlist_user_id'), table_name='tbl_wishlist')
    op.drop_index(op.f('ix_tbl_wishlist_book_id'), table_name='tbl_wishlist')
    op.drop_index(op.f('ix_tbl_order_user_id'), table_name='tbl_order')
    op.drop_index(op.f('ix_tbl_order_status'), table_name='tbl_order')
    op.drop_index(op.f('ix_tbl_order_created_at'), table_name='tbl_order')
    op.drop_index(op.f('ix_tbl_cart_item_user_id'), table_name='tbl_cart_item')
    op.drop_index(op.f('ix_tbl_cart_item_book_id'), table_name='tbl_cart_item')
    op.drop_index(op.f('ix_tbl_book_title'), table_name='tbl_book')
    op.drop_index(op.f('ix_tbl_book_is_active'), table_name='tbl_book')
    op.drop_index(op.f('ix_tbl_book_author'), table_name='tbl_book')
    # ### end Alembic commands ###
