"""add login attempt lock fields

Revision ID: 9b576245fcfd
Revises: 
Create Date: 2026-05-20 15:20:11.460475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b576245fcfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_auth_user', sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('tbl_auth_user', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_auth_user', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_auth_user', sa.Column('locked_reason', sa.String(length=255), nullable=True))
    op.add_column('tbl_auth_user', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_auth_user', 'password_changed_at')
    op.drop_column('tbl_auth_user', 'locked_reason')
    op.drop_column('tbl_auth_user', 'locked_at')
    op.drop_column('tbl_auth_user', 'locked_until')
    op.drop_column('tbl_auth_user', 'failed_login_attempts')
    # ### end Alembic commands ###
