"""add delivery columns to tbl_order

Revision ID: b6c3441a916c
Revises: 02f2594446ed
Create Date: 2026-06-03 22:56:41.585081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c3441a916c'
down_revision: Union[str, Sequence[str], None] = '02f2594446ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_order', sa.Column('delivery_way', sa.String(length=50), nullable=True))
    op.add_column('tbl_order', sa.Column('delivery_partner', sa.String(length=50), nullable=True))
    op.add_column('tbl_order', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_order', 'payment_method')
    op.drop_column('tbl_order', 'delivery_partner')
    op.drop_column('tbl_order', 'delivery_way')
    # ### end Alembic commands ###
