"""add delivery_address to tbl_order

Revision ID: bf5789aea121
Revises: b6c3441a916c
Create Date: 2026-06-03 23:48:31.236971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5789aea121'
down_revision: Union[str, Sequence[str], None] = 'b6c3441a916c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_order', sa.Column('delivery_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_order', 'delivery_address')
    # ### end Alembic commands ###
