"""add fcm_token to user_profile

Revision ID: d6fc571cf35d
Revises: 70a7538b9e86
Create Date: 2026-06-16 23:27:39.938768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fc571cf35d'
down_revision: Union[str, Sequence[str], None] = '70a7538b9e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user_profile', sa.Column('fcm_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_user_profile', 'fcm_token')
    # ### end Alembic commands ###
